### ISSUE TITLE
Channel invite: error when a user has an invitation to join a channel and the channel type change to 'protected' before the user accepts to join

### ISSUE THREAD

**Issue by tiny-chris** [JuanBraco/ft_transcendance#48]
- user A creates a channel 'chan' (public)
- as an owner/admin user A invites user B to join 'chan'
- before user B accepts, user A changes 'chan' type to a  'protected' (with pwd)
- when user B accepts, the invitation remains and there is an error (something went wrong/crash) --> we cannot do anything on the user B page (if no refresh)

**Comment by adcarnec** [comment]
hey, couldn't reproduce the pb: user B managed to enter password and send a msg 😅 : to be checked together?
