### ISSUE TITLE
user B invited stay blocked in the "invited to join a protected chanel mode" Even after entered the right password

### ISSUE THREAD

**Issue by JuanBraco** [JuanBraco/ft_transcendance#74]
User A sees User B joining the channel
The error is only on User B side
![Screenshot from 2023-11-15 19-43-33](https://github.com/JuanBraco/ft_transcendance/assets/107987620/ffbfbab2-4b5a-4a93-89ce-e7604d89232f)

**Comment by adcarnec** [comment]
not reproduced with current dev version
