### ISSUE TITLE
Error on double invitation from users A and C to play a game with user B (user B accepted DM invite from user A just before) --> Something went wrong on user A page

### ISSUE THREAD

**Issue by tiny-chris** [JuanBraco/ft_transcendance#80]
Case:

user A invites user B on DM
user B accepts the DM
user C invites user B to play a game
user A invites user B to play a game
--> user A : got screen on 'something went wrong'

**Comment by lmelard** [comment]
![Screenshot from 2023-11-16 16-01-40](https://github.com/JuanBraco/ft_transcendance/assets/86618739/349a9cc1-33b1-400a-bfc1-3bb21bc8b9a6)
